-- V10 비품(AST-001~005). 거점 종속. 개체(상태 덮어쓰기) vs 수량(입출고 이력) 분리.

-- 품목(관리 유형 명시 AST-001)
CREATE TABLE asset_item (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id     BIGINT       NOT NULL REFERENCES location (id),
    name            VARCHAR(200) NOT NULL,
    management_type VARCHAR(20)  NOT NULL CHECK (management_type IN ('INDIVIDUAL', 'QUANTITY')),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version         BIGINT       NOT NULL DEFAULT 0
);
CREATE TRIGGER trg_asset_item_updated_at BEFORE UPDATE ON asset_item
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX idx_asset_item_location ON asset_item (location_id);

-- 개체 비품(관리번호 유니크 AST-002, 상태 덮어쓰기, 폐기 보존 AST-004)
CREATE TABLE individual_asset (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_item_id    BIGINT       NOT NULL REFERENCES asset_item (id),
    asset_number     VARCHAR(100) NOT NULL UNIQUE,
    status           VARCHAR(20)  NOT NULL CHECK (status IN ('USING', 'STORAGE', 'REPAIR', 'DISCARDED')),
    acquisition_date DATE,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version          BIGINT       NOT NULL DEFAULT 0
);
CREATE TRIGGER trg_individual_asset_updated_at BEFORE UPDATE ON individual_asset
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX idx_individual_asset_item ON individual_asset (asset_item_id);

-- 수량 비품(품목당 1건, 현재 수량은 stock_transaction에서 파생 AST-003)
CREATE TABLE quantity_asset (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_item_id BIGINT      NOT NULL UNIQUE REFERENCES asset_item (id),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    version       BIGINT      NOT NULL DEFAULT 0
);
CREATE TRIGGER trg_quantity_asset_updated_at BEFORE UPDATE ON quantity_asset
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 입출고 이력(AST-003 AC1)
CREATE TABLE stock_transaction (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_item_id BIGINT      NOT NULL REFERENCES asset_item (id),
    tx_type       VARCHAR(10) NOT NULL CHECK (tx_type IN ('IN', 'OUT')),
    quantity      INT         NOT NULL CHECK (quantity >= 0),
    occurred_at   TIMESTAMPTZ NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    version       BIGINT      NOT NULL DEFAULT 0
);
CREATE TRIGGER trg_stock_transaction_updated_at BEFORE UPDATE ON stock_transaction
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX idx_stock_tx_item_time ON stock_transaction (asset_item_id, occurred_at);

-- 비품 사진(AST-005, 개체/품목 다중). 바이트는 MinIO, 메타만.
CREATE TABLE asset_photo (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_type   VARCHAR(20)  NOT NULL CHECK (owner_type IN ('ITEM', 'INDIVIDUAL')),
    owner_id     BIGINT       NOT NULL,
    file_name    VARCHAR(255) NOT NULL,
    content_type VARCHAR(150),
    size_bytes   BIGINT       NOT NULL CHECK (size_bytes >= 0),
    uploader_id  BIGINT       NOT NULL REFERENCES employee (id),
    object_key   VARCHAR(255) NOT NULL UNIQUE,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version      BIGINT       NOT NULL DEFAULT 0
);
CREATE TRIGGER trg_asset_photo_updated_at BEFORE UPDATE ON asset_photo
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX idx_asset_photo_owner ON asset_photo (owner_type, owner_id);
