-- V11 예약(RSV-001~007). 자원(차량/회의실) + 예약. 동시 겹침은 EXCLUSION 제약으로 차단(RSV-003 AC3).
-- btree_gist 확장은 V1에서 생성됨(resource_id 등가 비교 + 기간 겹침 연산을 한 GiST 인덱스에).

CREATE TABLE resource (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id    BIGINT       NOT NULL REFERENCES location (id),
    type           VARCHAR(20)  NOT NULL CHECK (type IN ('VEHICLE', 'MEETING_ROOM')),
    name           VARCHAR(200) NOT NULL,
    vehicle_model  VARCHAR(100),
    vehicle_number VARCHAR(50),
    equipment      VARCHAR(300),
    status         VARCHAR(20)  NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE')),
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version        BIGINT       NOT NULL DEFAULT 0
);
CREATE TRIGGER trg_resource_updated_at BEFORE UPDATE ON resource
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX idx_resource_location ON resource (location_id);

CREATE TABLE reservation (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_id     BIGINT       NOT NULL REFERENCES resource (id),
    reserver_id     BIGINT       NOT NULL REFERENCES employee (id),
    start_at        TIMESTAMPTZ  NOT NULL,
    end_at          TIMESTAMPTZ  NOT NULL,
    purpose         VARCHAR(300),
    headcount       INT          NOT NULL DEFAULT 0,
    note            VARCHAR(500),
    destination     VARCHAR(300),
    driver          VARCHAR(100),
    status          VARCHAR(20)  NOT NULL CHECK (status IN ('ACTIVE', 'CANCELLED')),
    cancel_reason   VARCHAR(500),
    cancelled_by_id BIGINT       REFERENCES employee (id),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version         BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT chk_reservation_period CHECK (start_at < end_at)
);
CREATE TRIGGER trg_reservation_updated_at BEFORE UPDATE ON reservation
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX idx_reservation_resource ON reservation (resource_id, status);

-- 동일 자원에 시간대가 겹치는 ACTIVE 예약 차단(RSV-003). 반열림 '[)' → 맞닿음 허용(AC2).
-- 동시 2요청은 한 건만 통과(AC3). 취소(CANCELLED)는 제외(부분 제약).
ALTER TABLE reservation ADD CONSTRAINT excl_reservation_overlap
    EXCLUDE USING gist (
        resource_id WITH =,
        tstzrange(start_at, end_at, '[)') WITH &&
    ) WHERE (status = 'ACTIVE');

CREATE TABLE resource_photo (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_id  BIGINT       NOT NULL REFERENCES resource (id),
    file_name    VARCHAR(255) NOT NULL,
    content_type VARCHAR(150),
    size_bytes   BIGINT       NOT NULL CHECK (size_bytes >= 0),
    uploader_id  BIGINT       NOT NULL REFERENCES employee (id),
    object_key   VARCHAR(255) NOT NULL UNIQUE,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version      BIGINT       NOT NULL DEFAULT 0
);
CREATE TRIGGER trg_resource_photo_updated_at BEFORE UPDATE ON resource_photo
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX idx_resource_photo_resource ON resource_photo (resource_id);
