-- V12 문서 아카이브(DOC-001~006). 결재 자동 보관 + 일반 업로드. 폴더 1 + 태그 N. 버전 이력.

CREATE TABLE folder (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(200) NOT NULL,
    parent_id  BIGINT       REFERENCES folder (id),
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version    BIGINT       NOT NULL DEFAULT 0
);
CREATE TRIGGER trg_folder_updated_at BEFORE UPDATE ON folder
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE tag (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version    BIGINT       NOT NULL DEFAULT 0
);
CREATE TRIGGER trg_tag_updated_at BEFORE UPDATE ON tag
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE archive_document (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           VARCHAR(300) NOT NULL,
    file_name       VARCHAR(255),
    source          VARCHAR(20)  NOT NULL CHECK (source IN ('APPROVAL', 'UPLOAD')),
    visibility      VARCHAR(20)  NOT NULL CHECK (visibility IN ('PUBLIC', 'INVOLVED_ONLY')),
    folder_id       BIGINT       REFERENCES folder (id),
    ref_document_id BIGINT       REFERENCES approval_document (id),
    registrar_id    BIGINT       REFERENCES employee (id),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version         BIGINT       NOT NULL DEFAULT 0
);
CREATE TRIGGER trg_archive_document_updated_at BEFORE UPDATE ON archive_document
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX idx_archive_document_folder ON archive_document (folder_id);
CREATE INDEX idx_archive_document_ref ON archive_document (ref_document_id);

CREATE TABLE archive_version (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    archive_document_id BIGINT       NOT NULL REFERENCES archive_document (id),
    version_no          INT          NOT NULL,
    object_key          VARCHAR(255) NOT NULL UNIQUE,
    uploader_id         BIGINT       NOT NULL REFERENCES employee (id),
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version             BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uq_archive_version UNIQUE (archive_document_id, version_no)
);
CREATE TRIGGER trg_archive_version_updated_at BEFORE UPDATE ON archive_version
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE document_tag (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    archive_document_id BIGINT      NOT NULL REFERENCES archive_document (id),
    tag_id              BIGINT      NOT NULL REFERENCES tag (id),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    version             BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT uq_document_tag UNIQUE (archive_document_id, tag_id)
);
CREATE TRIGGER trg_document_tag_updated_at BEFORE UPDATE ON document_tag
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX idx_document_tag_tag ON document_tag (tag_id);
