-- V13 알림(NOTI). 시스템 내 알림함 레코드(외부 발송 없음). 읽음/안읽음 상태. 무기한 보관(NOTI-004).

CREATE TABLE notification (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id BIGINT       NOT NULL REFERENCES employee (id),
    type         VARCHAR(40)  NOT NULL CHECK (type IN (
                 'APPROVAL_TURN', 'APPROVAL_APPROVED', 'APPROVAL_REJECTED', 'CONSENT_REQUEST',
                 'APPROVAL_ON_HOLD', 'DEPUTY_TURN', 'RESERVATION_CANCELLED_BY_ADMIN',
                 'RESERVATION_RESOURCE_REMOVED')),
    message      VARCHAR(500) NOT NULL,
    is_read      BOOLEAN      NOT NULL DEFAULT false,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version      BIGINT       NOT NULL DEFAULT 0
);
CREATE TRIGGER trg_notification_updated_at BEFORE UPDATE ON notification
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
-- 수신자별 안읽음 집계·목록 조회 인덱스(NOTI-003).
CREATE INDEX idx_notification_recipient ON notification (recipient_id, is_read);
