-- V2 FND 코어: 부서 · 임직원 · 역할범위.
-- 공통 규약(V1): created_at/updated_at TIMESTAMPTZ KST, version 낙관적 잠금, status VARCHAR+CHECK.

-- 부서(FND-002): 2~3단계, level CHECK, 물리 삭제 금지(status).
CREATE TABLE department (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_code   VARCHAR(50)  NOT NULL UNIQUE,
    name        VARCHAR(100) NOT NULL,
    parent_id   BIGINT       REFERENCES department (id),
    level       INT          NOT NULL CHECK (level BETWEEN 1 AND 3),
    status      VARCHAR(20)  NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE')),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version     BIGINT       NOT NULL DEFAULT 0
);
CREATE TRIGGER trg_department_updated_at BEFORE UPDATE ON department
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 임직원(FND-001): 사번·로그인ID 고유, 1인 1부서, 물리 삭제 금지(status).
CREATE TABLE employee (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_no               VARCHAR(50)  NOT NULL UNIQUE,
    login_id             VARCHAR(50)  NOT NULL UNIQUE,
    password_hash        VARCHAR(100) NOT NULL,
    name                 VARCHAR(100) NOT NULL,
    dept_id              BIGINT       NOT NULL REFERENCES department (id),
    position             VARCHAR(50),
    email                VARCHAR(255),
    phone                VARCHAR(50),
    status               VARCHAR(20)  NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE')),
    token_version        INT          NOT NULL DEFAULT 0,
    must_change_password BOOLEAN      NOT NULL DEFAULT false,
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version              BIGINT       NOT NULL DEFAULT 0
);
CREATE TRIGGER trg_employee_updated_at BEFORE UPDATE ON employee
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX idx_employee_dept ON employee (dept_id);

-- 역할범위(FND-006): (역할, 범위유형, 범위ID). 한 직원 다대다.
CREATE TABLE employee_role_scope (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT      NOT NULL REFERENCES employee (id),
    role_code   VARCHAR(30) NOT NULL CHECK (role_code IN
                ('GENERAL', 'DEPT_MANAGER', 'LOCATION_MANAGER', 'ASSET_MANAGER', 'SYS_ADMIN')),
    scope_type  VARCHAR(20) NOT NULL CHECK (scope_type IN ('NONE', 'DEPT', 'LOCATION')),
    scope_id    BIGINT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    version     BIGINT      NOT NULL DEFAULT 0
);
CREATE TRIGGER trg_employee_role_scope_updated_at BEFORE UPDATE ON employee_role_scope
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX idx_ers_employee ON employee_role_scope (employee_id);
