-- V3 리프레시 토큰(FND-003/004). 원문 대신 해시 저장, revoked 플래그.
CREATE TABLE refresh_token (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT       NOT NULL REFERENCES employee (id),
    token_hash  VARCHAR(100) NOT NULL,
    issued_at   TIMESTAMPTZ  NOT NULL,
    expires_at  TIMESTAMPTZ  NOT NULL,
    revoked     BOOLEAN      NOT NULL DEFAULT false,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version     BIGINT       NOT NULL DEFAULT 0
);
CREATE TRIGGER trg_refresh_token_updated_at BEFORE UPDATE ON refresh_token
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX idx_refresh_employee ON refresh_token (employee_id);
