-- V4 결재 공개키(FND-007/009). 공개키만 저장(개인키 미보관), 폐기 키도 보존.
CREATE TABLE signature_key (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT      NOT NULL REFERENCES employee (id),
    public_key  TEXT        NOT NULL,
    status      VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE', 'REVOKED')),
    revoked_at  TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    version     BIGINT      NOT NULL DEFAULT 0
);
CREATE TRIGGER trg_signature_key_updated_at BEFORE UPDATE ON signature_key
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX idx_signature_key_employee ON signature_key (employee_id);
