-- V5 결재 코어(AP-002/033/043): 문서 · 결재선 스냅샷 · 공휴일.

CREATE TABLE approval_document (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_type     VARCHAR(20)  NOT NULL CHECK (form_type IN ('EXPENSE', 'LEAVE', 'ASSET_REQ', 'GENERAL')),
    title         VARCHAR(200) NOT NULL,
    drafter_id    BIGINT       NOT NULL REFERENCES employee (id),
    draft_dept_id BIGINT       NOT NULL REFERENCES department (id),
    status        VARCHAR(20)  NOT NULL CHECK (status IN
                  ('DRAFT', 'IN_PROGRESS', 'ON_HOLD', 'APPROVED', 'REJECTED', 'WITHDRAWN')),
    current_round INT          NOT NULL DEFAULT 1,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0
);
CREATE TRIGGER trg_approval_document_updated_at BEFORE UPDATE ON approval_document
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX idx_approval_document_drafter ON approval_document (drafter_id);

-- 상신 시 복사·고정되는 결재선 스냅샷. round로 재상신 라운드 구분(과거 보존).
CREATE TABLE approval_line_snapshot (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT      NOT NULL REFERENCES approval_document (id),
    round       INT         NOT NULL DEFAULT 1,
    step_no     INT         NOT NULL,
    approver_id BIGINT      NOT NULL REFERENCES employee (id),
    step_type   VARCHAR(20) NOT NULL CHECK (step_type IN ('SEQUENTIAL', 'PARALLEL', 'CONSENT')),
    state       VARCHAR(20) NOT NULL CHECK (state IN
                ('PENDING', 'APPROVED', 'REJECTED', 'CONSENT_REJECTED', 'SKIPPED')),
    acted_at    TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    version     BIGINT      NOT NULL DEFAULT 0
);
CREATE TRIGGER trg_approval_line_snapshot_updated_at BEFORE UPDATE ON approval_line_snapshot
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX idx_als_document_round ON approval_line_snapshot (document_id, round);

-- 공휴일(AP-043). 날짜 유니크.
CREATE TABLE holiday (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    holiday_date DATE         NOT NULL UNIQUE,
    name         VARCHAR(100) NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version      BIGINT       NOT NULL DEFAULT 0
);
CREATE TRIGGER trg_holiday_updated_at BEFORE UPDATE ON holiday
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
