-- V6 대결·위임(AP-021/022) + 결재선 스냅샷에 실제 처리자 컬럼 추가.

CREATE TABLE delegation (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    approver_id BIGINT      NOT NULL REFERENCES employee (id),
    deputy_id   BIGINT      NOT NULL REFERENCES employee (id),
    active      BOOLEAN     NOT NULL DEFAULT true,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    version     BIGINT      NOT NULL DEFAULT 0
);
CREATE TRIGGER trg_delegation_updated_at BEFORE UPDATE ON delegation
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX idx_delegation_active ON delegation (active);

CREATE TABLE mandate (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mandator_id  BIGINT      NOT NULL REFERENCES employee (id),
    mandatee_id  BIGINT      NOT NULL REFERENCES employee (id),
    active       BOOLEAN     NOT NULL DEFAULT true,
    released_at  TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    version      BIGINT      NOT NULL DEFAULT 0
);
CREATE TRIGGER trg_mandate_updated_at BEFORE UPDATE ON mandate
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX idx_mandate_active ON mandate (active);

-- 실제 처리자(대결/위임 시 원 결재자와 다름). 스냅샷의 approver_id는 원 결재자로 보존(AP-002 AC3).
ALTER TABLE approval_line_snapshot ADD COLUMN acted_by_id BIGINT;
