-- V7 결재 양식 본문(AP-041/042/044/045): 양식별 본문 테이블.
-- 금액(지출/비품)은 수량×단가로 계산하므로 행에는 수량·단가만 저장(금액 컬럼 없음, AP-041 AC1).
-- 각 본문은 approval_document 1건과 1:1(document_id UNIQUE).

-- 지출결의서(AP-041)
CREATE TABLE expense_doc (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id  BIGINT       NOT NULL UNIQUE REFERENCES approval_document (id),
    expense_date DATE,
    payee        VARCHAR(200),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version      BIGINT       NOT NULL DEFAULT 0
);
CREATE TRIGGER trg_expense_doc_updated_at BEFORE UPDATE ON expense_doc
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE expense_doc_line (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT        NOT NULL REFERENCES approval_document (id),
    item_name   VARCHAR(200)  NOT NULL,
    quantity    INT           NOT NULL CHECK (quantity >= 0),
    unit_price  NUMERIC(15,2) NOT NULL CHECK (unit_price >= 0),
    note        VARCHAR(500),
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    version     BIGINT        NOT NULL DEFAULT 0
);
CREATE TRIGGER trg_expense_doc_line_updated_at BEFORE UPDATE ON expense_doc_line
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX idx_expense_doc_line_document ON expense_doc_line (document_id);

-- 휴가·근태 신청서(AP-042). 총 일수는 LeaveDaysCalculator로 산출(저장값은 산출 결과).
CREATE TABLE leave_doc (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id   BIGINT        NOT NULL UNIQUE REFERENCES approval_document (id),
    leave_type    VARCHAR(20)   NOT NULL,
    start_date    DATE          NOT NULL,
    end_date      DATE          NOT NULL,
    half_day      BOOLEAN       NOT NULL DEFAULT false,
    days          NUMERIC(5,1)  NOT NULL,
    reason        VARCHAR(500),
    substitute_id BIGINT        REFERENCES employee (id),
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    version       BIGINT        NOT NULL DEFAULT 0
);
CREATE TRIGGER trg_leave_doc_updated_at BEFORE UPDATE ON leave_doc
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 비품 신청서(AP-044). 수령 거점은 거점 모듈 도입 후 FK 연결(현재는 ID 보유).
CREATE TABLE asset_req_doc (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id         BIGINT       NOT NULL UNIQUE REFERENCES approval_document (id),
    desired_date        DATE,
    receive_location_id BIGINT       NOT NULL,
    reason              VARCHAR(500),
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version             BIGINT       NOT NULL DEFAULT 0
);
CREATE TRIGGER trg_asset_req_doc_updated_at BEFORE UPDATE ON asset_req_doc
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE asset_req_doc_line (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT        NOT NULL REFERENCES approval_document (id),
    item_name   VARCHAR(200)  NOT NULL,
    quantity    INT           NOT NULL CHECK (quantity >= 0),
    unit_price  NUMERIC(15,2) NOT NULL CHECK (unit_price >= 0),
    note        VARCHAR(500),
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    version     BIGINT        NOT NULL DEFAULT 0
);
CREATE TRIGGER trg_asset_req_doc_line_updated_at BEFORE UPDATE ON asset_req_doc_line
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX idx_asset_req_doc_line_document ON asset_req_doc_line (document_id);

-- 일반 품의서(AP-045). 본문 필수(AC1)는 서비스 검증 + NOT NULL.
CREATE TABLE general_doc (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT      NOT NULL UNIQUE REFERENCES approval_document (id),
    body        TEXT        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    version     BIGINT      NOT NULL DEFAULT 0
);
CREATE TRIGGER trg_general_doc_updated_at BEFORE UPDATE ON general_doc
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
