-- V8 결재 첨부 메타(AP-040 AC1). 바이트는 MinIO, DB에는 메타만(파일명·크기·업로더·문서ID·객체키).
-- object_key는 MinIO 내부 식별자로 외부 미노출(다운로드는 백엔드 경유).

CREATE TABLE attachment (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id  BIGINT       NOT NULL REFERENCES approval_document (id),
    file_name    VARCHAR(255) NOT NULL,
    content_type VARCHAR(150),
    size_bytes   BIGINT       NOT NULL CHECK (size_bytes >= 0),
    uploader_id  BIGINT       NOT NULL REFERENCES employee (id),
    object_key   VARCHAR(255) NOT NULL UNIQUE,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version      BIGINT       NOT NULL DEFAULT 0
);
CREATE TRIGGER trg_attachment_updated_at BEFORE UPDATE ON attachment
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX idx_attachment_document ON attachment (document_id);
