-- V9 거점(LOC-001~006). 물리 삭제 금지(status). 좌표는 지도 핀(LOC-002), 담당자 1명(LOC-001 AC2).
-- 사진은 다중(LOC-004) — 바이트는 MinIO, DB에는 메타만.

CREATE TABLE location (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_code VARCHAR(50)   NOT NULL UNIQUE,
    name          VARCHAR(200)  NOT NULL,
    address       VARCHAR(300),
    latitude      NUMERIC(9,6),
    longitude     NUMERIC(9,6),
    contact       VARCHAR(50),
    fax           VARCHAR(50),
    location_type VARCHAR(30),
    manager_id    BIGINT        REFERENCES employee (id),
    status        VARCHAR(20)   NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE')),
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    version       BIGINT        NOT NULL DEFAULT 0
);
CREATE TRIGGER trg_location_updated_at BEFORE UPDATE ON location
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX idx_location_status ON location (status);

CREATE TABLE location_photo (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id  BIGINT       NOT NULL REFERENCES location (id),
    file_name    VARCHAR(255) NOT NULL,
    content_type VARCHAR(150),
    size_bytes   BIGINT       NOT NULL CHECK (size_bytes >= 0),
    uploader_id  BIGINT       NOT NULL REFERENCES employee (id),
    object_key   VARCHAR(255) NOT NULL UNIQUE,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version      BIGINT       NOT NULL DEFAULT 0
);
CREATE TRIGGER trg_location_photo_updated_at BEFORE UPDATE ON location_photo
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE INDEX idx_location_photo_location ON location_photo (location_id);
